// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/germinator": {
    params: {};
  };
  "/nulay": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/germinator" | "/nulay";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "./routes/germinator/index.tsx": {
    id: "routes/germinator/index";
    page: "/germinator";
  };
  "./routes/nulay/index.tsx": {
    id: "routes/nulay/index";
    page: "/nulay";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home/index": typeof import("./app/routes/home/index.tsx");
  "routes/germinator/index": typeof import("./app/./routes/germinator/index.tsx");
  "routes/nulay/index": typeof import("./app/./routes/nulay/index.tsx");
};